### ISSUE TITLE
Upload data from CSV : internal exception 

### ISSUE THREAD

**Issue by mounzer-masri** [imona/adendum#35]
```
7:47:51.242 [jobLauncherTaskExecutor-3] ERROR com.imona.dev.SystemLogger - internal error
java.lang.RuntimeException: internal error
	at com.imona.engine.persist.ImonaPersister.save(ImonaPersister.java:121) ~[ImonaPersister.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItemsUsingDom(EntityItemWriter.java:55) [EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItems(EntityItemWriter.java:36) [EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.write(EntityItemWriter.java:22) [EntityItemWriter.class:na]
	at sun.reflect.GeneratedMethodAccessor44746.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [AopUtils.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) [DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) [DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [JdkDynamicAopProxy.class:4.0.3.RELEASE]
	at com.sun.proxy.$Proxy162.write(Unknown Source) [na:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:156) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:137) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:252) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:178) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:74) [ChunkOrientedTasklet.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:347) [TaskletStep$ChunkTransactionCallback.class:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [TransactionTemplate.class:4.0.3.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:261) [TaskletStep$2.class:na]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:76) [StepContextRepeatCallback.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368) [RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:214) [RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143) [RepeatTemplate.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:247) [TaskletStep.class:na]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:196) [AbstractStep.class:na]
	at org.springframework.batch.core.configuration.xml.SimpleFlowFactoryBean$DelegateStep.execute(SimpleFlowFactoryBean.java:175) [SimpleFlowFactoryBean$DelegateStep.class:na]
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:375) [AbstractJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.access$100(FlowJob.java:43) [FlowJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob$JobFlowExecutor.executeStep(FlowJob.java:135) [FlowJob$JobFlowExecutor.class:na]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60) [StepState.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:144) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:124) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:103) [FlowJob.class:na]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:266) [AbstractJob.class:na]
	at com.imona.batch.ComplexJobLauncher$1.run(ComplexJobLauncher.java:71) [ComplexJobLauncher$1.class:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
17:47:51.249 [jobLauncherTaskExecutor-3] ERROR o.s.batch.core.step.AbstractStep - Encountered an error executing the step
java.lang.RuntimeException: internal error
	at com.imona.engine.persist.ImonaPersister.save(ImonaPersister.java:121) ~[ImonaPersister.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItemsUsingDom(EntityItemWriter.java:55) ~[EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItems(EntityItemWriter.java:36) ~[EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.write(EntityItemWriter.java:22) ~[EntityItemWriter.class:na]
	at sun.reflect.GeneratedMethodAccessor44746.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[AopUtils.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) ~[DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) ~[DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[JdkDynamicAopProxy.class:4.0.3.RELEASE]
	at com.sun.proxy.$Proxy162.write(Unknown Source) ~[na:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:156) ~[SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:137) ~[SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:252) ~[SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:178) ~[SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:74) ~[ChunkOrientedTasklet.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:347) ~[TaskletStep$ChunkTransactionCallback.class:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[TransactionTemplate.class:4.0.3.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:261) ~[TaskletStep$2.class:na]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:76) ~[StepContextRepeatCallback.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368) ~[RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:214) ~[RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143) ~[RepeatTemplate.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:247) ~[TaskletStep.class:na]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:196) ~[AbstractStep.class:na]
	at org.springframework.batch.core.configuration.xml.SimpleFlowFactoryBean$DelegateStep.execute(SimpleFlowFactoryBean.java:175) [SimpleFlowFactoryBean$DelegateStep.class:na]
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:375) [AbstractJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.access$100(FlowJob.java:43) [FlowJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob$JobFlowExecutor.executeStep(FlowJob.java:135) [FlowJob$JobFlowExecutor.class:na]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60) [StepState.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:144) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:124) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:103) [FlowJob.class:na]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:266) [AbstractJob.class:na]
	at com.imona.batch.ComplexJobLauncher$1.run(ComplexJobLauncher.java:71) [ComplexJobLauncher$1.class:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
```

**Comment by mounzer-masri** [comment]
[HI_FNV_EK - Copy.txt](https://github.com/imona/adendum/files/1200792/HI_FNV_EK.-.Copy.txt)

**Comment by mtepe** [comment]
Bu hatanın acil olarak düzeltilmesi gerekmektedir. Veri yükleme işlemleri gerek test amaçlı, gerekse de finansal enstürman tablolarının güncel tutulabilmesi açısından yoğun olarak kullanılmaktadır.

**Comment by mounzer-masri** [comment]
13:34:05.329 [jobLauncherTaskExecutor-1] ERROR o.h.property.BasicPropertyAccessor - HHH000122: IllegalArgumentException in class: engine.domain.src.kat_grp, getter method of property: id
13:34:05.337 [jobLauncherTaskExecutor-1] ERROR com.imona.dev.SystemLogger - IllegalArgumentException occurred calling getter of engine.domain.src.kat_grp.id
org.hibernate.PropertyAccessException: IllegalArgumentException occurred calling getter of engine.domain.src.kat_grp.id

**Comment by mounzer-masri** [comment]
`URL: https://www.imona.com/store/
13:34:05.329 [jobLauncherTaskExecutor-1] ERROR o.h.property.BasicPropertyAccessor - HHH000122: IllegalArgumentException in class: engine.domain.src.kat_grp, getter method of property: id
13:34:05.337 [jobLauncherTaskExecutor-1] ERROR com.imona.dev.SystemLogger - IllegalArgumentException occurred calling getter of engine.domain.src.kat_grp.id
org.hibernate.PropertyAccessException: IllegalArgumentException occurred calling getter of engine.domain.src.kat_grp.id
	at org.hibernate.property.BasicPropertyAccessor$BasicGetter.get(BasicPropertyAccessor.java:187) ~[BasicPropertyAccessor$BasicGetter.class:4.1.1.Final]
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.getIdentifier(AbstractEntityTuplizer.java:341) ~[AbstractEntityTuplizer.class:4.1.1.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.getIdentifier(AbstractEntityPersister.java:4278) ~[AbstractEntityPersister.class:4.1.1.Final]
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:129) ~[DefaultMergeEventListener.class:4.1.1.Final]
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:76) ~[DefaultMergeEventListener.class:4.1.1.Final]
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:817) ~[SessionImpl.class:4.1.1.Final]
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:801) ~[SessionImpl.class:4.1.1.Final]
	at com.imona.engine.domain.DomSession.merge(DomSession.java:64) ~[DomSession.class:na]
	at com.imona.engine.domain.BATPersistentDomain.store(BATPersistentDomain.java:127) ~[BATPersistentDomain.class:na]
	at com.imona.engine.persist.ImonaPersister.save(ImonaPersister.java:100) ~[ImonaPersister.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItemsUsingDom(EntityItemWriter.java:55) [EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItems(EntityItemWriter.java:36) [EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.write(EntityItemWriter.java:22) [EntityItemWriter.class:na]
	at sun.reflect.GeneratedMethodAccessor44746.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [AopUtils.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) [DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) [DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [JdkDynamicAopProxy.class:4.0.3.RELEASE]
	at com.sun.proxy.$Proxy162.write(Unknown Source) [na:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:156) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:137) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:252) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:178) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:74) [ChunkOrientedTasklet.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:347) [TaskletStep$ChunkTransactionCallback.class:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [TransactionTemplate.class:4.0.3.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:261) [TaskletStep$2.class:na]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:76) [StepContextRepeatCallback.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368) [RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:214) [RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143) [RepeatTemplate.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:247) [TaskletStep.class:na]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:196) [AbstractStep.class:na]
	at org.springframework.batch.core.configuration.xml.SimpleFlowFactoryBean$DelegateStep.execute(SimpleFlowFactoryBean.java:175) [SimpleFlowFactoryBean$DelegateStep.class:na]
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:375) [AbstractJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.access$100(FlowJob.java:43) [FlowJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob$JobFlowExecutor.executeStep(FlowJob.java:135) [FlowJob$JobFlowExecutor.class:na]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60) [StepState.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:144) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:124) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:103) [FlowJob.class:na]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:266) [AbstractJob.class:na]
	at com.imona.batch.ComplexJobLauncher$1.run(ComplexJobLauncher.java:71) [ComplexJobLauncher$1.class:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@6b2e023d
	at sun.reflect.GeneratedMethodAccessor69574.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.hibernate.property.BasicPropertyAccessor$BasicGetter.get(BasicPropertyAccessor.java:164) ~[BasicPropertyAccessor$BasicGetter.class:4.1.1.Final]
	... 50 common frames omitted
13:34:05.342 [jobLauncherTaskExecutor-1] ERROR com.imona.dev.SystemLogger - internal error
java.lang.RuntimeException: internal error
	at com.imona.engine.persist.ImonaPersister.save(ImonaPersister.java:121) ~[ImonaPersister.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItemsUsingDom(EntityItemWriter.java:55) [EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItems(EntityItemWriter.java:36) [EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.write(EntityItemWriter.java:22) [EntityItemWriter.class:na]
	at sun.reflect.GeneratedMethodAccessor44746.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [AopUtils.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) [DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) [DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) [JdkDynamicAopProxy.class:4.0.3.RELEASE]
	at com.sun.proxy.$Proxy162.write(Unknown Source) [na:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:156) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:137) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:252) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:178) [SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:74) [ChunkOrientedTasklet.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:347) [TaskletStep$ChunkTransactionCallback.class:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [TransactionTemplate.class:4.0.3.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:261) [TaskletStep$2.class:na]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:76) [StepContextRepeatCallback.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368) [RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:214) [RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143) [RepeatTemplate.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:247) [TaskletStep.class:na]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:196) [AbstractStep.class:na]
	at org.springframework.batch.core.configuration.xml.SimpleFlowFactoryBean$DelegateStep.execute(SimpleFlowFactoryBean.java:175) [SimpleFlowFactoryBean$DelegateStep.class:na]
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:375) [AbstractJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.access$100(FlowJob.java:43) [FlowJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob$JobFlowExecutor.executeStep(FlowJob.java:135) [FlowJob$JobFlowExecutor.class:na]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60) [StepState.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:144) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:124) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:103) [FlowJob.class:na]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:266) [AbstractJob.class:na]
	at com.imona.batch.ComplexJobLauncher$1.run(ComplexJobLauncher.java:71) [ComplexJobLauncher$1.class:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]
13:34:05.347 [jobLauncherTaskExecutor-1] ERROR o.s.batch.core.step.AbstractStep - Encountered an error executing the step
java.lang.RuntimeException: internal error
	at com.imona.engine.persist.ImonaPersister.save(ImonaPersister.java:121) ~[ImonaPersister.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItemsUsingDom(EntityItemWriter.java:55) ~[EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.writeItems(EntityItemWriter.java:36) ~[EntityItemWriter.class:na]
	at com.imona.batch.entity.EntityItemWriter.write(EntityItemWriter.java:22) ~[EntityItemWriter.class:na]
	at sun.reflect.GeneratedMethodAccessor44746.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[AopUtils.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) ~[DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) ~[DelegatingIntroductionInterceptor.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[ReflectiveMethodInvocation.class:4.0.3.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[JdkDynamicAopProxy.class:4.0.3.RELEASE]
	at com.sun.proxy.$Proxy162.write(Unknown Source) ~[na:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:156) ~[SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:137) ~[SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:252) ~[SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:178) ~[SimpleChunkProcessor.class:na]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:74) ~[ChunkOrientedTasklet.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:347) ~[TaskletStep$ChunkTransactionCallback.class:na]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[TransactionTemplate.class:4.0.3.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:261) ~[TaskletStep$2.class:na]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:76) ~[StepContextRepeatCallback.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368) ~[RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:214) ~[RepeatTemplate.class:na]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143) ~[RepeatTemplate.class:na]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:247) ~[TaskletStep.class:na]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:196) ~[AbstractStep.class:na]
	at org.springframework.batch.core.configuration.xml.SimpleFlowFactoryBean$DelegateStep.execute(SimpleFlowFactoryBean.java:175) [SimpleFlowFactoryBean$DelegateStep.class:na]
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:375) [AbstractJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.access$100(FlowJob.java:43) [FlowJob.class:na]
	at org.springframework.batch.core.job.flow.FlowJob$JobFlowExecutor.executeStep(FlowJob.java:135) [FlowJob$JobFlowExecutor.class:na]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60) [StepState.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:144) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:124) [SimpleFlow.class:na]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:103) [FlowJob.class:na]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:266) [AbstractJob.class:na]
	at com.imona.batch.ComplexJobLauncher$1.run(ComplexJobLauncher.java:71) [ComplexJobLauncher$1.class:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_11]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_11]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_11]`
